// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package MiniProject3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IncrementerClient is the client API for Incrementer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncrementerClient interface {
	Increment(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type incrementerClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementerClient(cc grpc.ClientConnInterface) IncrementerClient {
	return &incrementerClient{cc}
}

func (c *incrementerClient) Increment(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/Inc.Incrementer/Increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementerServer is the server API for Incrementer service.
// All implementations must embed UnimplementedIncrementerServer
// for forward compatibility
type IncrementerServer interface {
	Increment(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedIncrementerServer()
}

// UnimplementedIncrementerServer must be embedded to have forward compatible implementations.
type UnimplementedIncrementerServer struct {
}

func (UnimplementedIncrementerServer) Increment(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedIncrementerServer) mustEmbedUnimplementedIncrementerServer() {}

// UnsafeIncrementerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncrementerServer will
// result in compilation errors.
type UnsafeIncrementerServer interface {
	mustEmbedUnimplementedIncrementerServer()
}

func RegisterIncrementerServer(s grpc.ServiceRegistrar, srv IncrementerServer) {
	s.RegisterService(&Incrementer_ServiceDesc, srv)
}

func _Incrementer_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementerServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inc.Incrementer/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementerServer).Increment(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Incrementer_ServiceDesc is the grpc.ServiceDesc for Incrementer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Incrementer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Inc.Incrementer",
	HandlerType: (*IncrementerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Increment",
			Handler:    _Incrementer_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inc/inc.proto",
}
